App:
  name: CurrencyExchangeApp
  port: :3000

Database:
  dsn: root:246810810@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: "11"
  MaxOpenCons: "114"

DeepSeek:
  api_key: "sk-c05fc54f470d406884c2c98ec8c97db3"
  base_url: "https://api.deepseek.com/v1/chat/completions"
  model: "deepseek-chat"